

apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-sa
  namespace: tf-ssd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-sa-admin
subjects:
  - kind: ServiceAccount
    name: terraform-sa
    namespace: tf-ssd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-upgrade-ssd
  namespace: tf-ssd
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: terraform-sa
      restartPolicy: Never
      containers:
        - name: terraform
          image: hashicorp/terraform:1.6.0
          workingDir: /workspace/ssd-infra
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e

              echo "Installing git..."
              apk add --no-cache git bash

              echo "Cloning OpsMx SSD Helm chart..."
              rm -rf /tmp/enterprise-ssd
              git clone --branch ${GIT_BRANCH} ${GIT_REPO_URL} /tmp/enterprise-ssd

              echo "Cloning Terraform configuration..."
              rm -rf /workspace/ssd-infra
              git clone --branch ${TF_BRANCH} ${TF_REPO_URL} /workspace/ssd-infra
              cd /workspace/ssd-infra

              echo "Initializing Terraform..."
              terraform init

              echo "Applying Terraform (Install / Upgrade)..."
              terraform apply -auto-approve \
                -var="namespace=${SSD_NAMESPACE}" \
                -var="cert_manager_installed=${CERT_MANAGER_INSTALLED}"

              echo "Terraform SSD deployment completed successfully."
          env:
            - name: GIT_REPO_URL
              value: "https://github.com/NaveenBalagouni/argocd-terraform.git"
            - name: GIT_BRANCH
              value: "main"

            - name: TF_REPO_URL
              value: "ttps://github.com/OpsMx/enterprise-ssd.git""
            - name: TF_BRANCH
              value: "2025-11"

            - name: SSD_NAMESPACE
              value: "tf-ssd"

            - name: CERT_MANAGER_INSTALLED
              value: "true"

          volumeMounts:
            - name: workspace
              mountPath: /workspace

      volumes:
        - name: workspace
          emptyDir: {}
