apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-sa
  namespace: ssd-tf-argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-sa-admin
subjects:
  - kind: ServiceAccount
    name: terraform-sa
    namespace: ssd-tf-argocd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: terraform-job
  namespace: ssd-tf-argocd
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: terraform-sa
      restartPolicy: Never
      containers:
        - name: terraform
          image: hashicorp/terraform:1.6.0
          workingDir: /workspace
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e


              echo "Cloning Terraform repo..."
              git clone --branch ${GIT_BRANCH} ${GIT_REPO_URL} /workspace/ssd-infra
              cd /workspace/ssd-infra

              echo "Using kubeconfig..."
              export KUBECONFIG=/root/.kube/config

              echo "Terraform init..."
              terraform init

              echo "Terraform plan..."
              terraform plan 

              echo "Terraform apply..."
              terraform apply -auto-approve 

              echo "Terraform completed successfully"
          env:
            - name: GIT_REPO_URL
              value: "https://github.com/NaveenBalagouni/argocd-terraform.git"
            - name: GIT_BRANCH
              value: "main"
          volumeMounts:
            - name: kubeconfig
              mountPath: /root/.kube
              readOnly: true
            - name: workspace
              mountPath: /workspace
      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
        - name: workspace
          emptyDir: {}
