

apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-sa
  namespace: tf-ssd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-sa-admin
subjects:
  - kind: ServiceAccount
    name: terraform-sa
    namespace: tf-ssd
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: terraform-upgrade-ssd-
  namespace: tf-ssd
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  backoffLimit: 0
  template:
    spec:
      serviceAccountName: terraform-sa
      restartPolicy: Never

      containers:
        - name: terraform
          image: hashicorp/terraform:1.6.0
          workingDir: /workspace/ssd-infra
          command:
            - /bin/sh
            - -c
          args:
            - |
              set -e
              apk add --no-cache git bash

              rm -rf /tmp/enterprise-ssd
              git clone --branch "${GIT_BRANCH}" "${GIT_REPO_URL}" /tmp/enterprise-ssd

              rm -rf /workspace/ssd-infra
              git clone --branch "${TF_BRANCH}" "${TF_REPO_URL}" /workspace/ssd-infra
              cd /workspace/ssd-infra

              terraform init
              terraform apply -auto-approve \
                -var="namespace=${SSD_NAMESPACE}" \
                -var="cert_manager_installed=${CERT_MANAGER_INSTALLED}"

          env:
            - name: GIT_REPO_URL
              value: "https://github.com/opsmx/enterprise-ssd.git"
            - name: GIT_BRANCH
              value: "2025-11"
            - name: TF_REPO_URL
              value: "https://github.com/your-org/ssd-terraform.git"
            - name: TF_BRANCH
              value: "main"
            - name: SSD_NAMESPACE
              value: "tf-ssd"
            - name: CERT_MANAGER_INSTALLED
              value: "true"

          volumeMounts:
            - name: kubeconfig
              mountPath: /root/.kube
              readOnly: true
            - name: workspace
              mountPath: /workspace

      volumes:
        - name: kubeconfig
          secret:
            secretName: kubeconfig
        - name: workspace
          emptyDir: {}
